### PR TITLE
#16615232 transition from transfix to zanata translator

### PR DESCRIPTION
**Pull request by bencyn**
#### Title
Transition from transfix translator to zanata opensource translator

#### Description
Wger is a fully open source software. Depending on closed source software is, to a certain extent, unethical and should be avoided if possible. Hence the need to transition from transifex to Zanata, an opensource translator. 

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?

Visit the translation project https://translate.zanata.org/iteration/view/wg-fortem/v1

#### Checklist:
- [x] integrate zanata opensource translator
- [x] update zanata language translations with wger locales

#### PT stories
[#166152328](https://www.pivotaltracker.com/story/show/166152328)

### CODE REVIEW

**Review by Tevinthuku — APPROVED** [review]
This works as expected. Awesome work shifting from Transfix to Zanata.

**Review by justMuriithi — APPROVED** [review]
Great job moving us to an open source solution that is Zanata. Works seamlessly.

**Review by misocho — APPROVED** [review]
The translations work as expected. Good job 👍🏾

**Review by Kimaiyo077 — APPROVED** [review]
The new open source software translates as expected. Good work @bencyn how you made the transition smooth

**Review by martinMutuma — APPROVED** [review]
Awesome work. The translations are working as expected.

**Review by michael-basweti — APPROVED** [review]
works as required

**Pull request merged**
