### PR TITLE
166152334 enable managers to delete or deactivate trainers

### PR DESCRIPTION
**Pull request by Tevinthuku**
#### Title

 Managers should be able to delete or deactivate trainers

#### Description
N/B: Login as admin or gym manager and have the token in the Authorization headers.
1. login as admin `http://localhost:8000/en/admin/`
then go to `http://localhost:8000/en/gym/list` to create a new gym
2. Create 2 trainers in the gym
image

3. endpoint for toggling a trainer's activation status.
`POST http://localhost:8000/api/v2/gym/<gymId>/trainers/<trainerId>/toggle`

image

image

4. an endpoint for deleting a trainer
`DELETE http://localhost:8000/api/v2/gym/<gymId>/trainers/<trainerId>/`

image

5. an endpoint for listing trainers that groups them as either active or inactive trainers. (Does not require authentication)
`GET http://localhost:8000/api/v2/gym/<gymId>/trainers`

image

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?
- [x] - Unit tests
- [x] - Integration tests

#### Checklist:

- [x] - create tests for viewing list of trainers
- [x] - create an endpoint for viewing trainers
- [x] - correct logic for fetching trainers
- [x] - write endpoint for toggling a trainer's status 
- [x] - can now delete a trainer from a gym
- [x] - create a generic function to update or delete trainer from gym
- [x] - improved list trainers format

#### PT stories
[#166152334](https://www.pivotaltracker.com/n/projects/2350046/stories/166152334)

### CODE REVIEW

**Review by justMuriithi — APPROVED** [review]
Great job on adding the functionality of managers to delete or deactivate trainers. I particularly like the use of abstraction in dispatch_trainer_action which increases maintainability. This looks ready to go!!

**Review by misocho — APPROVED** [review]
I can delete or deactivate trainers from my end. Good job 👍🏾

**Review by Kimaiyo077 — APPROVED** [review]
Good job. The endpoints for toggling a trainer's activity are working as expected and the one for deleting a trainer is working too. I especially like the error messages that are shown, for example, when trying to toggle the activity status of a trainer who is not part of the selected gym, it informs you that the trainer is not part of the gym instead of just saying the trainer does not exist. Awesome work

**Review by michael-basweti — APPROVED** [review]
nice work. works as expected

**Pull request merged**
