### PR TITLE
166152323 reset cache on muscle delete

### PR DESCRIPTION
**Pull request by Tevinthuku**
#### Title

Resetting cache on muscle delete

#### Description
Initially, after deleting a muscle, it still appeared under the muscle overview page. This was caused by a failure to reset muscle cache on delete.
The cache should be reset after a muscle has been deleted such that the deleted muscle in not visible from the exercises page.
#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue) 

- [ ] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?
-Log in to the application as an admin, visit the muscle menu under the exercise tab
`localhost:8000/en/exercise/muscle/admin-overview/`
-Click on the add muscle button and add a muscle name.
-Visit the add exercise tab and add a new exercise focusing on the new muscle added.
-Go back to the muscles menu and delete the recently added muscle and verify that the muscle no-longer included under the muscle overview page.

#### Checklist:

- [x] - create a signal on muscle delete to delete the muscle overview page cache
- [x] - create a signal on muscle creation to delete the overview page cache
- [x] - create a reusable function to delete the overview page cache on muscle deletion and creation

#### PT stories
[#166152323](https://www.pivotaltracker.com/n/projects/2350046/stories/166152323)

### CODE REVIEW

**Review by misocho — APPROVED** [review]
The muscles are now getting cleared from the cache on delete. Good job 👍🏾

**Review by martinMutuma — APPROVED** [review]
Good works. The gym is cache is cleared after deletion. 
I like that you also added a function to clear cache when adding a muscle

**Review by justMuriithi — APPROVED** [review]
Great job resetting the cache when a muscle is deleted. Works as expected.

**Review by bencyn — APPROVED** [review]
Great job on reusing code functions. The feature works as expected

**Review by Kimaiyo077 — APPROVED** [review]
Great work. It's good you fixed both when a muscle is added and deleted.

**Review by michael-basweti — APPROVED** [review]
works as expected

**Pull request merged**
