### PR TITLE
#166263767 Travis and Coveralls integration

### PR DESCRIPTION
**Pull request by misocho**
#### Title
Travis and Coveralls integration
#### Description
Currently, we don't have a Travis and coveralls badge on the README. There is a need to have both Travis and coveralls integrated so that we can monitor our tests and the coverage.
#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [ ] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [x] Task / Chore

- [ ] This change requires a documentation update
#### How has this been Tested?
View the [README](https://github.com/andela/wg-fortem/tree/task/166263767-integrate-travis) on the `task/166263767-integrate-travis` branch
#### Checklist
- [x] Integrate the app with Travis
- [x] Add Travis badge in the README
- [x] Add coveralls badge in the README
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/166263767

### CODE REVIEW

**Review by justMuriithi — APPROVED** [review]
Great work integrating Travis and coveralls. Now we can have seamless integration knowing that our tests are passing and that the coverage is good.

**Review by Tevinthuku — APPROVED** [review]
Awesome work on configuring `.travis.yml` to make sure that Travis builds and tests our App successfully. The README also shows the badges appropriately and gives an accurate score of the app's build status and coverage. Good job.

**Review by martinMutuma — APPROVED** [review]
Quite thoughtful to have only Travis and not both Travis and Circle CI since they serve the same function, and also integrating coveralls and the badges. This is okay

**Review by michael-basweti — APPROVED** [review]
This looks good and meets the required expectations.

**Pull request merged**
