### PR TITLE
166152321-Import weight from Fitbit API

### PR DESCRIPTION
**Pull request by martinMutuma**
#### Title
Import weight from Fitbit API

#### Description
Users should be able to pull in weight information from Fitbit. This will allow us to also to import data from places like calorie counter.

*How can this be tested*
`install requirements `
1. create an account at [Fitbit](https://www.fitbit.com) also create a few weight logs on Fitbit
2. On WGER App go to the dropdown on user link and click on `Fitbit synch`
Follow prompts from Fitbit 
image

3. Got to `/en/weight/overview/` on the options button click on `Import from Fitbit`
image
4. The data is fetched from Fitbit
image

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?
- [x] Unit tests
#### Checklist:
- [x] Add Fitbit integration
- [x] Import weight log from Fitbit
- [x] Write tests for the feature  

#### PT stories
[#166152321](https://www.pivotaltracker.com/story/show/166152321)

### CODE REVIEW

**Comment by misocho** [comment]
Awesome work @martinMutuma. We can now import our weights from Fitbit.

**Review by misocho — APPROVED** [review]
Awesome work @martinMutuma. We can now import our weights from Fitbit.

**Review by Kimaiyo077 — APPROVED** [review]
Excellent work Martin. The feature works as expected and I was able to import my weights from Fitbit. I was also able to view the differences between each of the logs.

**Review by Tevinthuku — APPROVED** [review]
Awesome work integrating the Fitbit API into Wger. It works as expected and I can now view the weight I logged in Fitbit right from my dashboard.

**Review by justMuriithi — APPROVED** [review]
Great job. The Fitbit integration brings in awesome sync between wger and Fitbit. I love the ease by which we can now import logs from Fitbit.

**Review by michael-basweti — APPROVED** [review]
works according to the task description

**Pull request merged**
