### PR TITLE
166152326 Allows comparison of members

### PR DESCRIPTION
**Pull request by justMuriithi**
#### Title

This PR allows for the comparison of members' weight data

#### Description

When two users are training together it would be useful to see a comparison of some sorts. Two graphs showing the users' weight data gives a good visual impression of the comparison

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Can This Be Manually Tested?
To be able to test the feature, check out the branch `story/166152326-comparison-of-members` and then `python manage.py runserver`.

- Login as a gym manager

- Navigate to the URL `http://127.0.0.1:8000/en/gym/<gym_id>/members` on your browser

image

- Select 2 users

image

- Compare

image

#### Checklist:
- [x] Adds a means to compare weight data of 2 members
- [x] Assigns comparison functionality to the gym manager

#### PT stories
[#166152326](https://www.pivotaltracker.com/story/show/166152326)

### CODE REVIEW

**Review by Tevinthuku — APPROVED** [review]
This works as expected. I can now compare the weights of two users successfully

**Review by misocho — APPROVED** [review]
Good work with the comparison graphs. We can now visually compare two users.

**Review by Kimaiyo077 — APPROVED** [review]
I was able to compare weight entries of two users graphically which can be helpful data. Nice work @justMuriithi

**Review by michael-basweti — APPROVED** [review]
works according to the task description

**Pull request merged**
