### PR TITLE
166434770 Create and list gym records

### PR DESCRIPTION
**Pull request by bencyn**
#### Title
An admin or gym manager should be able to list all registered gyms via a Rest API endpoint as well as create one.

#### Description
N/B: Login as admin or gym manager and have the token in the Authorization headers.

1. Gym list endpoint `GET http://127.0.0.1:8000/api/v2/gym/`

image

2. Gym record create endpoint `POST http://127.0.0.1:8000/api/v2/gym/`
Post data
```
{
    "name": "Trm Gymster",
    "phone": "790561841",
    "email": "gachugua@gmail.com",
    "owner": "kevin",
    "zip_code": "523",
    "city": "Nairobi",
    "street": null
}
```

image

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?

- [ ] - Unit tests
- [x] - Integration tests

#### Checklist:

- [x] - create tests for viewing list for gyms
- [x] - create tests for creating a gym record
- [x] - write an endpoint for listing gym records
- [x] - write an endpoint for creating a gym record

#### PT stories
[#166434770](https://www.pivotaltracker.com/n/projects/2350046/stories/166434770)

### CODE REVIEW

**Review by Tevinthuku — APPROVED** [review]
Good job on ensuring that only the admins can create and list gyms.
I've tested and seen that a gym is indeed created and can be viewed in the list of gyms.

**Review by martinMutuma — COMMENTED** [review]
Good work on the Gym create and list endpoints, both endpoints work as expected. 
Would you consider making the gym name unique and also have a minimum length for the gym name 
However, this change would require input from the team 
image

**Comment by bencyn** [comment]
> Good work on the Gym create and list endpoints, both endpoints work as expected.
> Would you consider making the gym name unique and also have a minimum length for the gym name
> However, this change would require input from the team
> image

This duly noted I'll create a bug story from this once I get input from the team.

**Review by martinMutuma — APPROVED** [review]
Good work, Create the bug story as agreed

**Review by misocho — APPROVED** [review]
The endpoint works. Let's have a bug story on the next sprint to fix the issue with having identical gym names.

**Review by michael-basweti — APPROVED** [review]
Does an amazing job at delivering the task

**Pull request merged**
