### PR TITLE
166152320 add user registration through api

### PR DESCRIPTION
**Pull request by martinMutuma**
#### Title
It should be possible to create new users via the API. 

#### Description
This is because external apps might need to register accounts on behalf of their users without having to send them over to the wger instance.
REST API consumers that want to create users need a special right that has to be given on demand.
Users Created via the REST API should have a special flag so that it's possible to see who created them

1. Create User Endpoint `api/v2/user/`
data 
```json
{
   "username":"Benson",
   "password" : "admin"
}
```
2. Assign Create user permission Endpoint `/api/v2/user/allow-create-users`
```json
{
  "username":"benson"
}
```
3. Assign Create user permission command `python manage.py add-user-rest-api <username>`
4. Delete Create user permission command `python manage.py add-user-rest-api <username> --delete`
5. List users with create user permission `python manage.py list-user-rest-api`

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [X] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?
- [x] Unit tests

  
#### Checklist:
- [x] Add Register-user Api endpoint
- [x] Add User registration log for users created via API
- [x] Add command to grant users create user permission
- [x] Add Tests for all functionality 

#### PT stories
[#166152320](https://www.pivotaltracker.com/n/projects/2350046/stories/166152320)
#### Screenshots
Register user endpoint
image
Assign user create user permission endpoint 
image

### CODE REVIEW

**Review by Kimaiyo077 — APPROVED** [review]
All the endpoints work as expected on my end. Good work on adding the commands to easily grant permissions, revoke them and list all the users with the permissions. Good work

**Review by Tevinthuku — COMMENTED** [review]
I'm particularly intrigued by the commands, I think they are really helpful, in the sense that You can list the users that can create accounts for other users and can revoke and grant the permission to do so from the terminal is really great work.

I, however, noticed a small issue, if I attempt to register a user without having the `Authorization` field it returns a `[500] 'AnonymousUser' object has no attribute 'userprofile'`

image

Other than that everything else checks out

**Comment by martinMutuma** [comment]
> I'm particularly intrigued by the commands, I think they are really helpful, in the sense that You can list the users that can create accounts for other users and can revoke and grant the permission to do so from the terminal is really great work.
> 
> I, however, noticed a small issue, if I attempt to register a user without having the `Authorization` field it returns a `[500] 'AnonymousUser' object has no attribute 'userprofile'`
> 
> image
> 
> Other than that everything else checks out

working on it

**Comment by martinMutuma** [comment]
> I'm particularly intrigued by the commands, I think they are really helpful, in the sense that You can list the users that can create accounts for other users and can revoke and grant the permission to do so from the terminal is really great work.
> 
> I, however, noticed a small issue, if I attempt to register a user without having the `Authorization` field it returns a `[500] 'AnonymousUser' object has no attribute 'userprofile'`
> 
> image
> 
> Other than that everything else checks out

Thank you for pointing out that ... I have resolved the issue 
image

**Review by michael-basweti — APPROVED** [review]
Amazing job on creating CLI commands. The task meets the expected standards

**Pull request merged**
