### PR TITLE
166570682 fix login feature

### PR DESCRIPTION
**Pull request by bencyn**
#### Title
Fix login functionality

#### Description

Fix login functionality by upgrading to the new django2 form of login

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue) 

- [ ] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?

-  check out the branch 
   `feature/166570682-fix-login`

-  run the command  
   `Invoke bootstrap-wger  --settings-path path-to-your-settings-file` and then `python manage.py runserver`.

-  Navigate to the URL `http://127.0.0.1:8000/en/user/login`  and you should be to view the login page.

#### Checklist:
- [x] Fix login page
- [x] Update login page functionality

#### PT stories
[#166570682](https://www.pivotaltracker.com/story/show/166570682)

#### Screenshots
image

### CODE REVIEW

**Review by Tevinthuku — APPROVED** [review]
Good job fixing the login functionality. Works as expected. 👍

**Review by justMuriithi — APPROVED** [review]
Great job fixing the login. We can now access protected URLs with ease.

**Review by martinMutuma — APPROVED** [review]
Login works. We can now access the application without having to register users afresh
Neat implementation too.

**Review by misocho — APPROVED** [review]
Great job fixing the login page 👍🏾

**Review by michael-basweti — APPROVED** [review]
Solved the bug that existed

**Pull request merged**
