### PR TITLE
166152329 Update muscles list and exercises

### PR DESCRIPTION
**Pull request by Kimaiyo077**
#### Title
New muscles should be added to the existing muscle list and exercises updated to accommodate the new muscles.

#### Description
When a user navigates to the muscles overview page, they should be able to view the updated muscle list and corresponding exercises. The new muscles are; Lateral Deltoid, Obliquus Externus Abdominis, Posterior Deltoid, and Forearms.

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Can This Be Tested?
To be able to test the feature, check out the branch `story/166152329-update-muscle-list`, run the command  `Invoke load-fixtures --settings-path path-to-your-settings-file` and then `python manage.py runserver`.
Navigate to the URL `http://127.0.0.1:8000/en/exercise/muscle/overview/` and you should be able to see the new muscles

Note that the Lateral Deltoid muscle is not easy to see but it is along the shoulder between the Anterior and Posterior Deltoid muscles

Screenshot 2019-06-11 at 20 18 35

#### Checklist:
- [x] Add SVG files for new muscles
- [x] Update muscles fixtures with new muscles
- [x] Update exercises with the new muscles

#### PT stories
[#166152329](https://www.pivotaltracker.com/story/show/166152329)

### CODE REVIEW

**Review by martinMutuma — APPROVED** [review]
Awesome work, the muscles are well visible on the UI

**Review by justMuriithi — APPROVED** [review]
Great job updating the muscle list and the exercises for the respective muscles.

**Review by Tevinthuku — APPROVED** [review]
This works as expected. The new muscle items are mapped appropriately on the body.

**Review by misocho — APPROVED** [review]
Good job on updating the muscle list.

**Review by bencyn — APPROVED** [review]
Great work. Love how you created vector svgs for muscles. Kudos

**Review by michael-basweti — APPROVED** [review]

**Pull request merged**
