### PR TITLE
#166152333 Add support for macrocycle, mesocycle and microcycle

### PR DESCRIPTION
**Pull request by bencyn**
#### Title
Adds support for macrocycle(Up to a year), mesocycle(2-6 weeks) and microcycle(1 week).

#### Description
Macro is an annual plan, meso is phase of training with a duration of between 2-6 weeks and micro is instead only a week.

This is needed for sports periodization ( powerlifting, weightlifting, strongman, etc ) or at least to create fitness programs drafted on more than only one week.

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Has This Been Tested?

-  check out the branch 
   `story/166152333-macrocycle-mesocycle-microcycle-support`

-  run the command  
   `nvoke bootstrap-wger --settings-path ./wger/settings.py --no-start-server` and then `python manage.py runserver`.

- run server and open browser
  `python manage.py migrate`

- run server and open browser
  `python manage.py  runserver`

- navigate to workouts page and click on Add workout
image

- set a cycle type
image

  select the cycle you want, put a description and save. Depending on which cycle you chose, one of 
  the following should appear and  the popups while setting a timeline

`Microcycle` 
image
image

`Mesocycle`
image
image

`Macrocycle`
image
image

#### Checklist:
- [x] Add workout cycle fixtures in weeks and month as well days
- [x] Add a workout_plan field in the core_days_of_week model
- [x] Add cycle options field in the manager_workout model
- [x] Add set cycle type  modal link in the single workout view

#### PT stories
[#166152333](https://www.pivotaltracker.com/story/show/166152333)

### CODE REVIEW

**Review by Tevinthuku — APPROVED** [review]
This works as expected. Good job on adding the different workout cycles and also updating the fixtures.
Point to note is I had to drop the DB for this to work.

**Review by Kimaiyo077 — APPROVED** [review]
Good Job Benson. I like how each cycle can further be customized into specific days, weeks or months.

**Review by misocho — APPROVED** [review]
Works as expected though we have to drop the DB.

**Review by martinMutuma — APPROVED** [review]
Awesome work. However, I had to drop DB to test the feature. For future features, we should find a better way to solve the issues that arise when we change fixtures.
Update this command in your PR description `nvoke bootstrap-wger --settings-path ./wger/settings.py --no-start-server`

**Review by michael-basweti — APPROVED** [review]
works as per the requirements

**Pull request merged**
