### PR TITLE
166152338 Adds hover over body part to get exercises

### PR DESCRIPTION
**Pull request by justMuriithi**
#### Title

A user should be able to hover a body part to obtain a list of exercises

#### Description

When a user hovers over a body part, they should be able to get exercises for that body part. This creates a great and memorable user experience

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [x] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

#### How Can This Be Tested?
To be able to test the feature, check out the branch `story/166152338-hover-body-get-exercises` and then `python manage.py runserver`.
Navigate to the URL `http://127.0.0.1:8000/en/exercise/muscle/overview/` on your browser
Hover over the image. 
Screenshot 2019-06-11 at 20 18 35
#### Checklist:
- [x] Adds svg for front muscles
- [x] Adds svg for back muscles
- [x] Adds CSS styling to allow hover

#### PT stories
[#166152338](https://www.pivotaltracker.com/story/show/166152338)

### CODE REVIEW

**Review by martinMutuma — COMMENTED** [review]
Good work, the feature works as expected. I like the speed with which you have implemented the feature.

**Review by martinMutuma — APPROVED** [review]
Good work, the feature works as expected. I like the speed with which you have implemented the feature.

**Review by misocho — APPROVED** [review]
The feature works seamlessly. Good job 👍🏾

**Review by Kimaiyo077 — APPROVED** [review]
Works well, On hovering above the muscles I was able to see the exercises related to it. I like that it also highlights the name of the muscle. Good work

**Review by Tevinthuku — APPROVED** [review]
This works as expected. I believe that it's an even more convenient way of getting a muscle's exercises, particularly when you do not know the muscle's name. 
Good Job 👍

**Review by bencyn — APPROVED** [review]
Love how you have implemented  Highlight on hover js function. Great job

**Review by michael-basweti — APPROVED** [review]
works according to the description

**Pull request merged**
