### PR TITLE
#166152315 Fix linting issues

### PR DESCRIPTION
**Pull request by Kimaiyo077**
#### Title
Fix linting problems raised by flake8

#### Description

This PR fixes all the linting issues raised by flake8. 
The code now adheres to the pep8 style guide and rules set in the Andela engineering playbook. 

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) 

- [ ] New feature (non-breaking change which adds functionality) 

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

- [ ] This change requires a documentation update

- [x] Task / Chore

#### Checklist:

- [x] Fix python linting issues
- [x] Integrate hound on GitHub
-  [x] Add hound.yml file to activate hound on GitHub
-  [x] Fix failing tests caused by deleting unused imports
-  [x] Add 'noqa' to lines that should be ignored by flake8
-  [x] Update Requirements file
-  [x] Update README

#### PT stories

[#166152315](https://www.pivotaltracker.com/story/show/166152315)

### CODE REVIEW

**Review by misocho — APPROVED** [review]
It's great that all the linting issues were addressed. Good job 🙌🏼

**Review by justMuriithi — APPROVED** [review]
Great work fixing the linting issues and adhering to PEP8 guidelines.

**Review by martinMutuma — APPROVED** [review]
Well done. Length of lines has been reduced to fit the agreed standard by the team and also Pep8 guidelines.

**Review by michael-basweti — APPROVED** [review]
This is good work, it captures the linting errors as per the standards set by the group

**Pull request merged**
